### ISSUE TITLE
When a pr-preview is deployed, keep using the `head_ref` in pr-deploy

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#1044]
Restore:

```         

 ssh dokku@$DOKKU_HOST -C "dokku git:set ${{ env.SUBDOMAIN }} deploy-branch ${{ github.head_ref }}"
``` 

 The deploy branch needs to stay, that's very important because that's the branch which gets tested.
Am I missing something?

_Originally posted by @chrisjsimpson in https://github.com/Subscribie/subscribie/pull/1042#discussion_r1068387379_

**Comment by joeltejeda** [comment]
This is to solve the #1043
