### ISSUE TITLE
as a shop owner after customer accepting a plan with terms and condition I can't see the Agreed terms and service

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#1050]
**Is your feature request related to a problem? Please describe.**
as a shop owner after customer accepting a plan with terms and condition I can't see the Agreed terms and service

**Describe the solution you'd like**
As a shop owner i would like to see the agreed terms and service

**Additional context**

the error line: 

[Add any other context or screenshots about the feature request here.](https://github.com/Subscribie/subscribie/blob/0b55694b74a36b449075fe5acab10c1b3f461d1a/subscribie/blueprints/admin/templates/admin/documents/list_documents.html#L101)

**Comment by chrisjsimpson** [comment]
@joeltejeda additional context https://github.com/Subscribie/subscribie/blob/master/tests/browser-automated-tests-playwright/tests/939_subscriber_order_free_plan_with_terms_and_conditions.js
