### ISSUE TITLE
As a subscriber I can pay it forward to a pot, which the shop owner can use to pay other subscribers outstanding payments (hardship fund)

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#1065]
**Is your feature request related to a problem? Please describe.**

We got talking about hardship and the "cost of living crisis" in the UK (not unique to the UK).

Sometimes the club volunteers pay for their members membership, and the clubs pause the subscription for two months etc.

This reminded me of the hardship fund idea.

E.g. not all players are in the same economic situation, *perhaps* they might want to pay into an anonymous "pay it forward" (great film) bucket which can be used for others to use if they hit hard times..

**Describe the solution you'd like**

(Requires thought)

Some sort of:

- As a subscriber I can pay into a pot 'donate' my subscription (e.g. double) which becomes available to shop owners to cover payments for other members
- How hardship presently works for some organisations: 
  - An email will be sent (usually from a parent) to a club manager saying they're currently struggling. Club may pause their payments "we tend to pause their payments for two months". 
  - Complications: "Sometimes volunteers will pay out of their own pocket for a member"

Empathy, privacy, controls , channels of communications, fairness, and potentially escrow considerations. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jimmyedagawa78** [comment]
Overview of the UI

![whiteboard](https://user-images.githubusercontent.com/30567984/217526164-9ebbb5ca-c5a8-45fc-b727-0aa4ed752a5e.png)

**Comment by jimmyedagawa78** [comment]
Overview of the UI 

![whiteboard (1)](https://user-images.githubusercontent.com/30567984/217527444-afec2bd8-be05-4093-a2cd-27341b79de94.png)

**Comment by chrisjsimpson** [comment]
@joeltejeda we will likely want/need to refactor `stripe_create_checkout_session` to use that concept for creating a checkout session

The key part is creating a stripe checkout session id, however, since these transactions are not associated with any plan, some refactoring will likely be needed. 

The key part being: https://github.com/Subscribie/subscribie/blob/3dfd591fa7c345f26a57ab719dda817cda37bddb/subscribie/blueprints/checkout/__init__.py#L417-L429


The full `stripe_create_checkout_session`

https://github.com/Subscribie/subscribie/blob/3dfd591fa7c345f26a57ab719dda817cda37bddb/subscribie/blueprints/checkout/__init__.py#L279-L429
