### ISSUE TITLE
Test share plan url test does not actually test the share url

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#1167]
**Is your feature request related to a problem? Please describe.**

Test share plan url test does not actually test the share url

**Describe the solution you'd like**

Verify the share url loads

**Describe alternatives you've considered**

**Additional context**

#491

https://github.com/Subscribie/subscribie/blob/9f96487ed77d8666ad9373933ebf26c6c38bb82d/tests/browser-automated-tests-playwright/tests/491_shop_owner_share_private_plan_url.js#L4

**Comment by joeltejeda** [comment]
https://github.com/Subscribie/subscribie/blob/9f96487ed77d8666ad9373933ebf26c6c38bb82d/tests/browser-automated-tests-playwright/tests/491_shop_owner_share_private_plan_url.js#L12

it goes to the private plan url and check if the page loads
