### ISSUE TITLE
As a shop owner, i would like to add a quarterly plan

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#1200]
**Is your feature request related to a problem? Please describe.**
As a shop owner, i would like to add a quarterly plan

**Describe the solution you'd like**
At the moment, plans can be weekly, monthly, yearly and as a shop owner i would like to add quarterly too

**Comment by chrisjsimpson** [comment]
Duplicate
https://github.com/Subscribie/subscribie/issues/1170
