### ISSUE TITLE
Cannot build local env

### ISSUE THREAD

**Issue by chiho13** [Subscribie/subscribie#135]
Getting this error after running 'flask run'

<img width="858" alt="Screenshot 2020-03-25 at 00 04 28" src="https://user-images.githubusercontent.com/5622684/77488316-bd31df00-6e2c-11ea-9fc6-003e9e570a0a.png">

**Comment by chrisjsimpson** [comment]
Thanks @chiho13  sorry for the experience!

Please follow the updated instructions here: https://github.com/Subscribie/subscribie/commit/03843bf255ee881e1755944847a47b39b75143bc

**Comment by chrisjsimpson** [comment]
Have updated the readme with more up to date instructions https://github.com/Subscribie/subscribie/blob/03843bf255ee881e1755944847a47b39b75143bc/README.md#contributing-for-development

**Comment by chrisjsimpson** [comment]
glad we got it working together offline on your mac, thanks @chiho13 closing this now
