### ISSUE TITLE
As a shop owner I can upload content which my subscribers can see

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#192]
**Is your feature request related to a problem? Please describe.**
As a shop owner when subscribers Subscribe, then they should gain access to content I share. 

**Describe the solution you'd like**
Needs refinement.

**Describe alternatives you've considered**

**Additional context**

- Dropbox integration?
- Amazon S3?

**Comment by jimmyedagawa78** [comment]
Here is a guide on how to add files to your shop in Subscribie. 
https://subscribie.co.uk/blog/how-to-add-files-to-your-shop-for-subscribers/
