### ISSUE TITLE
As a Shop Owner I can go back through the sign up processs without loosing information 

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#200]
**Is your feature request related to a problem? Please describe.**
Currently if a shop owner goes bach through the sign up process and information already entered on future pages is lost and this has to be re-entered. This also means the information is saved as multiple listings.

**Describe the solution you'd like**
The information should remain on the sign up sheets while the customer switches between pages. It should only be saved to the system when fully submitted and payment is taken.

**Describe alternatives you've considered**
Currently the store owner may have to re-enter information. Non completed sign ups that are saved before sign up is complete can be removed from the site.

- [x] Make information typed in during the sign up process to remain in the form while the shop owner switches between different pages

**Comment by chrisjsimpson** [comment]
> Only save the information when the sign up is complete and a final submit is made and payment complete
Moved to https://github.com/Subscribie/subscribie/issues/242
