### ISSUE TITLE
Sign up confirmation email contains errors

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#203]
**Is your feature request related to a problem? Please describe.**
The initial email confimring the sign up process is complete contains various errors. It refers to the Shop Owner as "John" Regardless of name, and refers to the payment amount as unknown. the email is also sent twice (Juplicate) as is the email containing the Shop Owners web address.

**Describe the solution you'd like**
Ensure the confirmation email refers to the Shop Owner with their name as entered during the set up process and the correct amount, £10 for three months or £6.99 monthly depending on option selected.
Also ensure both emails are only sent once.

**Describe alternatives you've considered**
The email could not be addressed directly to avoid the issue of misnaming people. However this is less personal and may seem less secure / professional.

- [x] Correct the confirmation email so that it addresses the correct name.
- [ ] Correct the confirmation email so that the amount paid is correct, rather than displaying 'unknown'
- [ ] Ensure the confirmation email is only sent once
- [ ] Ensure the email containing Shop Owners web address is only sent once

**Comment by chrisjsimpson** [comment]
https://github.com/Subscribie/subscribie/commit/8dfd54ad1428602242eb638720f7e28524bea9cf has been merged into main ( Correct the confirmation email so that it addresses the correct name.)

**Comment by chrisjsimpson** [comment]
Welcome email

https://github.com/Subscribie/subscribie/blob/master/subscribie/emails/welcome.jinja2.html
