### ISSUE TITLE
As a Shop Owner I can mark payments as shipped/completed/fulfilled etc

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#204]
**Is your feature request related to a problem? Please describe.**
Currently the payment records can't be marked with any descriptive terms other than paid. This can make it hard for Shop Owners to keep track of their work.

**Describe the solution you'd like**
Give Shop Owners the ability to mark their customer payments as complete

**Describe alternatives you've considered**
Shop Owners can currently track order details on GoCardless but this requires a separate login

- [x] Determine a set of defined terms for Shop Owners to use (eg packed, shipped, fulfilled)
- [x] Allow Shop Owners to mark payments / orders with this set criteria

**Comment by chrisjsimpson** [comment]
Simplified implementation: Shop owners can mark payments as 'complete' meaning they are processed orders.

**Comment by chrisjsimpson** [comment]
![image](https://user-images.githubusercontent.com/1718624/85335328-bf134900-b4d4-11ea-9923-f87a1c4af915.png)

@Anpoli13 
@Svyatoslav-Polishchuk 
@KatherineAS
