### ISSUE TITLE
As a Shop Owner I understand the process of connecting Stripe

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#210]
**Is your feature request related to a problem? Please describe.**
There are a few errors in the wording of the instrucctions of adding stripe to their account which may cause confusion.

**Describe the solution you'd like**
Change the sdescriptions to accurately match the terms used on the Stripe site and make it easy for the shop owner

- [ ] Update wording to "Reveal test key token" rather than live
- [ ] Use Stripe signup flow (if they have one) rather than getting users to connect developer account

**Comment by joeltejeda** [comment]
https://subscribie.co.uk/blog/how-to-create-a-stripe-account-and-link-it-to-subscribie/
