### ISSUE TITLE
View Customers page not found

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#219]
**Is your feature request related to a problem? Please describe.**
From the shop owner dashboard, clicking the 'view customers' link lead to a 'Something's gone wrong' page

**Describe the solution you'd like**
Correct this page break issue so the page correctly shows a list of current customers / subscribers

**Describe alternatives you've considered**
Recent payments would still be viewable in GoCardless though this wouldnt suggest whether they are still subscribed

- [ ] Debug page link to source issue
- [ ] Fix to have a fully functioning link to a list of current customers

**Comment by chrisjsimpson** [comment]
These links have been superseded by upcoming payments and 'subscribers' page. 

TODO remove the old pages.
