### ISSUE TITLE
As a Shop Owner I can see new pages I've added

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#222]
**Is your feature request related to a problem? Please describe.**
Currently shop owners can add new pages, but once created they do not appear on the shops menu and thus the pages arent visable to the shop owner or customers

**Describe the solution you'd like**
For the Titles of the new pages to appear as tabs on their shop menu so theyre easily accesible to the shop owners and customers

- [ ] Ensure new page titles are automatically added to the shop's menu
- [ ] Allow shop owners to rearrange the order of these pages in the menu
- [ ] Allow shop owners to hide pages from customers

**Comment by chrisjsimpson** [comment]
Broken rest into own issues.

https://github.com/Subscribie/subscribie/issues/239

https://github.com/Subscribie/subscribie/issues/240
