### ISSUE TITLE
As a Shop Owner I can control which frequency options are available to Customers

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#232]
**Is your feature request related to a problem? Please describe.**
Subscriptions can only be charged monthly

**Describe the solution you'd like**
Allow a variety of frequency options to be available for shop owners to offer on their items (eg bi-weekly, monthly, bi-monthly). Allow shop owners to choose which are available on each different item they sell

**Describe alternatives you've considered**

**Additional context**
Shop Owners can list items as a bi-monthly delivery but payment is still taken monthly, so they can charge half as much each month, though this may be confusing and not an obvious as an option to shop owners.

- [ ] Have a variety of frequency options availble for shop owners to offer
- [ ] Allow shop owners to offer a different selction of frequencies for each option they sell
- [ ] Allow shop owners to offer customers to group deliveries together 
- [ ] Ensure options are optional and default to 'off' ie shop owners must approve the options before being available to customers

**Comment by chrisjsimpson** [comment]
![image](https://user-images.githubusercontent.com/1718624/88489668-91b33280-cf8d-11ea-89d1-dbbcfec786e2.png)

**Comment by chrisjsimpson** [comment]
Admin view:
![image](https://user-images.githubusercontent.com/1718624/88490636-d5f60100-cf94-11ea-98db-7ec29a506a50.png)
