### ISSUE TITLE
Improve spacing above add plan save button 

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#267]

**Comment by chrisjsimpson** [comment]
When on mobile, during user testing it was observed that the user's thumb accidentally presses the 'home' link below rather than the Save button 

![image](https://user-images.githubusercontent.com/1718624/93870870-bdb90e80-fcc5-11ea-9d0e-7ba74e6f6471.png)

**Comment by Anpoli13** [comment]
#294
