### ISSUE TITLE
iframe embed, remove header / footer

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#298]
**Is your feature request related to a problem? Please describe.**
When embedding a shop into a website 

"We would need to be able to remove the header section completely"
"We would need to remove the footer section completely"

**Describe the solution you'd like**
By Default, when the shop is embedded, do not show the header & footer of the shop, only show the plans.

**Additional context**

Make use of iframe auto resizer to automatically resize iframe https://github.com/davidjbradshaw/iframe-resizer

**Comment by havenswift-hosting** [comment]
It would also make sense to hide the footer section on the /account/login and account/forgot-password pages as well.  Needed for white label solution

**Comment by chrisjsimpson** [comment]
> It would also make sense to hide the footer section on the /account/login and account/forgot-password pages as well. Needed for white label solution
@havenswift-hosting 
In the meantime that can be achieved by using the style module with some css to display: none the footer etc.

**Comment by chrisjsimpson** [comment]
Need to add SameSite policy for cookies

**Comment by chrisjsimpson** [comment]
Closing this as feature is completed

Proposed _enhancement_ to this using auto resizing: https://github.com/Subscribie/subscribie/issues/316
