### ISSUE TITLE
Enhancement : add custom SMTP email settings

### ISSUE THREAD

**Issue by havenswift-hosting** [Subscribie/subscribie#304]
This would allow emails to be sent from a shop owners own domain if required

**Comment by chrisjsimpson** [comment]
The reply-to field may instead be set from the Shop owners dashboard -> Emails -> Set reply to

**Comment by havenswift-hosting** [comment]
Setting the reply-to field is not a solution and is barely a work-around. Adding SMTP email sending settings is standard in most applications these days
