### ISSUE TITLE
Typo on choice groups - customer facing

### ISSUE THREAD

**Issue by havenswift-hosting** [Subscribie/subscribie#320]
When in choice groups there is a typo (choise) - see attached image

![WhatsApp Image 2020-11-05 at 14 42 00](https://user-images.githubusercontent.com/6114431/98256175-28709180-1f76-11eb-91aa-b87243fffffe.jpeg)

**Comment by chrisjsimpson** [comment]
Thanks @havenswift-hosting Fixed https://github.com/Subscribie/subscribie/commit/3e56501d5f1afddfb1a99ecb89d5ab7c443ce0aa
