### ISSUE TITLE
Custom email template validation

### ISSUE THREAD

**Issue by havenswift-hosting** [Subscribie/subscribie#324]
When creating a custom email confirmation template

1) If there is an error in the template, it would be good to have a bit more information if possible as to what the error is ?
  See https://github.com/Subscribie/subscribie/issues/324#issuecomment-735003506 
2) <strike> It should also not completely clear the custom email template just because there is an error that means it cannot be saved !  </strike>
  Fixed in dd6e689

**Comment by havenswift-hosting** [comment]
3. Also the template radio selection choice should be retained.  It should default to "Default template" but if "Custom template" is then chosen, that choice should then be retained - you shouldnt have to make the selection each time

**Comment by chrisjsimpson** [comment]
> If there is an error in the template, it would be good to have a bit more information if possible as to what the error is ?

The above is the current behaviour. e.g:

![image](https://user-images.githubusercontent.com/1718624/100487425-6dfd2600-3100-11eb-925a-702d01a041a7.png)
 

A preview (separate issue) will be useful to less technical users
