### ISSUE TITLE
Stripe payment confirmation for one off item

### ISSUE THREAD

**Issue by victoriakmiles** [Subscribie/subscribie#333]
Just tested a one off product, the confirmation page is blank and the auto confirmation email is the same as it would be for an ongoing subscription product.

**Comment by chrisjsimpson** [comment]
Hi @victoriakmiles 


It sounds like the welcome email may have been customised incorrectly. The default welcome email is not the same:

https://github.com/Subscribie/subscribie/blob/d6b17dabe4e1de516c05c2e86ddeb04689e0c217/subscribie/emails/welcome.jinja2.html#L8

I suggest using the default template or adapting it to your needs
