### ISSUE TITLE
Integrate new onboarding styling

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#465]

**Comment by chrisjsimpson** [comment]
![image](https://user-images.githubusercontent.com/1718624/111038882-1e2e3a80-8423-11eb-8033-c6b2fa16cafd.png)
White background/text

**Comment by chrisjsimpson** [comment]
![image](https://user-images.githubusercontent.com/1718624/111038915-428a1700-8423-11eb-9b0c-51809dc03691.png)
white backgroun/text

**Comment by chrisjsimpson** [comment]
google sign in styling 

![image](https://user-images.githubusercontent.com/1718624/111038936-59c90480-8423-11eb-9161-91a58f363b24.png)

**Comment by chrisjsimpson** [comment]
update navigation with href to pages http://subscriptionwebsitebuilder.co.uk/

**Comment by med-achraf-abdelbari** [comment]
Done bugs fixed please check https://github.com/Subscribie/onboarding-theme-temp/commit/050c131b178d18ba1d8f4cbf48cbae0a23512cf2

**Comment by chrisjsimpson** [comment]
Thanks @med-achraf-abdelbari I will look asap 🙂
