### ISSUE TITLE
Plan descriptions to collapse by default

### ISSUE THREAD

**Issue by Anpoli13** [Subscribie/subscribie#483]
**Is your feature request related to a problem? Please describe.**
The plan description to collapse by default because this allows shops owners to 
- say what they want to say
- avoids

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisjsimpson** [comment]
@Anpoli13  I have reviewed locally. looks good to me :) ready for pr?

**Comment by chrisjsimpson** [comment]
merged :)
