### ISSUE TITLE
Issuing refund in subscribies shop

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#503]
**Is your feature request related to a problem? Please describe.**
Customers would like to issue refunds to clients from their shops

**Describe the solution you'd like**
A feature inside the subscribers near the Actions: Pause | cancel subscriptions with a refund button.

**Comment by chrisjsimpson** [comment]
@joeltejeda Thanks Joel good detail 👌 please may you start on the html to add "refund" <a> tag on the subscribers list?
