### ISSUE TITLE
As a shop owner, the documentation shows me how to create categories and put plans into categories 

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#540]
**Is your feature request related to a problem? Please describe.**
As a shop owner, the documentation shows me how to create categories and put plans into categories 

**Describe the solution you'd like**
A tutorial document example showing how As a shop owner, the documentation shows me how to create categories and put plans into categories 

**Describe alternatives you've considered**

**Additional context**

**Comment by joeltejeda** [comment]
https://subscribie.co.uk/blog/how-to-use-categories-in-subscribie/
