### ISSUE TITLE
As a shop owner, I would like to add an FAQ section to my website

### ISSUE THREAD

**Issue by Laurenmceil** [Subscribie/subscribie#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisjsimpson** [comment]
Closed until need. Would benefit from a prerequisite of genetic components. Right now, shoppers can achieve the same effect by creating a plain page and choose to write an faq as the content.
