### ISSUE TITLE
Migrate old shops 

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#673]
**Is your feature request related to a problem? Please describe.**

 old shops (using GoCardless)  require too much special care and maintenance bourdon. 

**Describe the solution you'd like**
upgrade or remove old shops because they're a burden to maintain. 

It's easy to move shop, what I more interesting how to move their active subscribers from GoCardless to Stripe)

**Describe alternatives you've considered**

**Additional context**

#162

**Comment by joeltejeda** [comment]
There are no more old shops remaining for the maintenance
