### ISSUE TITLE
QA new deployment #17

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#68]
Steps to QA:

- Visit https://subscribie.co.uk
- click 'start now'
- fill out new shop form with [shop name] of your choice 
- submit form
- Choose 'Standard plan'
- Pay with stripe test card 4545 4545 4545 4545
- Pay with Gocardless test account. use the sort code 200000 and the account number 55779911
- You should see "thank you" page

- visit the new shop: https://[shop name].subscribie.shop
- login to your shop using the email address entered during sign-up

Known issues:
- thank you page does not display link to live shop
- uploaded pictures do not show in shop

**Comment by ThomasHui** [comment]
Selected "Standard Plan" 
Expected: Payment page
Observed: Thank You Page

**Comment by chrisjsimpson** [comment]
Cheers @ThomasHui, thanks to you this has been narrowed down to https://github.com/Subscribie/subscribie/issues/69 a fix will be rolled out asap. :+1:

**Comment by Svyatoslav-Polishchuk** [comment]
**Selected "Standard Plan"**
Expected: One-off payment checkout page
Observed: Direct debit setup page

---

**Have been redirected to Thank You page**
Expected: An active link to the guide after `Read our guide full of practical steps you can take right now to make your subscription website a sucess.` paragraph (btw, there is missing `c` in `success`).
Observed: `How to make my website successful` link with missing `href` attribute.

---

**After reading through Thank You page**
Expected: Instructions what should be my next steps (my shop link, login link, email, etc).
Observed: Nothing

---

**Visited the new shop: https://qabysvayt.subscribie.shop**
Expected: My shop page
Observed: Error 503 (`503 Service Temporarily Unavailable`)
