### ISSUE TITLE
playwright test tags 

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#726]
**Is your feature request related to a problem? Please describe.**
In some situations while doing tests with playwright is necessary to exclude some tests or only run specific tests depending in the  nature of tests.

**Describe the solution you'd like**
Using tags in playwright test to exclude test or only do specific tests

**Additional context**
https://docs.google.com/document/d/1rwAlOfPrNr8AhpiK1l51dNnivf2hR2e4qDuAIDNl00A/edit?usp=sharing

**Comment by chrisjsimpson** [comment]
Completed
