### ISSUE TITLE
As a new shop owner, I was not able to find the register button

### ISSUE THREAD

**Issue by jimmyedagawa78** [Subscribie/subscribie#778]
**Is your feature request related to a problem? Please describe.**
As a new potential shop owner, while I was browsing the website to register as a new user, I was unable to find the registration button. I was able to find the login button at the top of the page but was confused when I could not find a button for new users to register.

**Describe the solution you'd like**
When I go to the home page, I would expect a button that says register near the login button. After clicking the login button, I expect to be taken to the Start Building page (https://subscribie.co.uk/start-building) where I am able to create a new account as a potential customer of Subscribie.
![Github](https://user-images.githubusercontent.com/30567984/154246802-0aacf2c7-e3da-45c4-8ccf-1cd7e99a9696.png)

**Describe alternatives you've considered**

**Additional context**
This is an issue I faced when visiting subscribie.co.uk for the first time.

- template https://github.com/Subscribie/subscribie/blob/431265800d85242c91f0e6b85b1e8d51aac43519/subscribie/themes/theme-builder/builder/layout.html#L115

**Comment by chrisjsimpson** [comment]
https://github.com/Subscribie/subscribie/blob/431265800d85242c91f0e6b85b1e8d51aac43519/subscribie/themes/theme-builder/builder/layout.html#L115
