### ISSUE TITLE
As a new user, I found some of the overhead menu links missing when adjusting the resolution of the website

### ISSUE THREAD

**Issue by jimmyedagawa78** [Subscribie/subscribie#779]
**Is your feature request related to a problem? Please describe.**
As a new user, when I was browsing through the website, I encountered an issue where the menu links in the overhead section of the website go missing when adjusting the size of the browser window. 
![image](https://user-images.githubusercontent.com/30567984/154262840-2599f3bd-95b2-4f1b-81ca-3f51f1e6f843.png)

**Describe the solution you'd like**
When I visit the website, I expect to see the overhead links visible for interacting or shown when clicking a drop-down menu.
![image](https://user-images.githubusercontent.com/30567984/154262946-ae380bea-4bb6-4f18-bc5c-f27c8cdae187.png)

**Describe alternatives you've considered**

**Additional context**
This issue is faced when adjusting the browser window.

**Comment by joeltejeda** [comment]
the button to open navbar-toggler-icon can be seen from the screenshot

**Comment by chrisjsimpson** [comment]
More Detail: This issue happens at breakpoint: 998 x 539

observe: 'pricing' is missing and other menu items.

![image](https://user-images.githubusercontent.com/1718624/165395539-6aef3a1d-5bfd-4fb6-939d-f1fb50a9a171.png)
