### ISSUE TITLE
As a shop owner, I can change the font color of the home page

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#793]
**Is your feature request related to a problem? Please describe.**
As a shop owner, I can change the font color of the home page

Sometimes shop owners might want to change the backgroud to a  lighter color and the default black color are hard to see. 

**Describe the solution you'd like**
Allow shop owner to change their font color with a pallet of colors

**Comment by chrisjsimpson** [comment]
Resolved by https://github.com/Subscribie/subscribie/pull/812
