### ISSUE TITLE
update envsubst

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#794]
**Is your feature request related to a problem? Please describe.**
PATH_TO_SITES and PATH_TO_RENAME_SCRIPT are not part of the template

**Describe the solution you'd like**

+PATH_TO_SITES=${PATH_TO_SITES}
+PATH_TO_RENAME_SCRIPT=${PATH_TO_RENAME_SCRIPT}

**Comment by chrisjsimpson** [comment]
This has been done
