### ISSUE TITLE
UWSGI cron refresh-invoices is exceding uwsgi_read_timeout

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#841]
**Is your feature request related to a problem? Please describe.**
UWSGI cron refresh-invoices is exceding uwsgi_read_timeout

**Describe the solution you'd like**
Using Threads to allow the cron refresh-invoices to run in another thread so it doesn't stop uwsgi from running.

**Comment by chrisjsimpson** [comment]
Resolved by https://github.com/Subscribie/subscribie/pull/842

See also https://github.com/Subscribie/subscribie/pull/846
